# Generated by Django 3.0 on 2021-02-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier',
            table='New supplier',
        ),
    ]
